import { useEffect, useRef, useState } from 'react'
import { getImageDimensions } from '../../data/image-dimensions'

interface VideoProps {
  /** The youtube unique identifier token */
  youtube: string;
  /** Human-readable title; the accessible name of both the facade and the player */
  name: string;
  /** Load the thumbnail eagerly — for above-the-fold entries only */
  eager?: boolean;
}

// Self-hosted still generated by `npm run resize-images` from
// originals/archive/img/motion/<id>.jpg. Self-hosting (rather than hotlinking
// i.ytimg.com) means the page makes no request to Google until the visitor
// asks for the video. See README.md ("Adding a new motion video").
function thumbnailPath(youtube: string) {
  return `/archive/img/motion/${youtube}.webp`;
}

// autoplay=1 is safe here because the iframe only ever mounts in response to a
// click, which is the play intent. youtube-nocookie.com defers YouTube's
// tracking cookies until playback actually starts.
function embedSrc(youtube: string) {
  return `https://www.youtube-nocookie.com/embed/${youtube}?autoplay=1`;
}

export function Video({ youtube, name, eager = false }: VideoProps) {
  // Each player is ~1 MB of JavaScript, so it is not rendered until asked for;
  // until then the box holds a static thumbnail (a "facade").
  const [playing, setPlaying] = useState(false);
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const thumbnail = thumbnailPath(youtube);
  const dimensions = getImageDimensions(thumbnail);

  // The swap unmounts the button that had focus, which would drop focus to
  // <body>. Move it into the player instead, so a keyboard visitor lands on the
  // controls they just asked for. Only reachable after a deliberate activation.
  useEffect(() => {
    if (playing) iframeRef.current?.focus();
  }, [playing]);

  return (
    <div className="video">
      {playing ? (
        <iframe
          ref={iframeRef}
          src={embedSrc(youtube)}
          title={name}
          loading="lazy"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          referrerPolicy="strict-origin-when-cross-origin"
          allowFullScreen
        />
      ) : (
        <button
          type="button"
          className="video-facade"
          onClick={() => setPlaying(true)}
        >
          <img
            src={thumbnail}
            alt=""
            width={dimensions?.width}
            height={dimensions?.height}
            loading={eager ? 'eager' : 'lazy'}
            fetchPriority={eager ? 'high' : undefined}
            decoding="async"
          />
          <svg className="video-play" viewBox="0 0 100 100" aria-hidden="true">
            <circle cx="50" cy="50" r="47" fill="none" stroke="currentColor" strokeWidth="3" />
            <path d="M40 31 L72 50 L40 69 Z" fill="currentColor" />
          </svg>
          <span className="visually-hidden">Play {name}</span>
        </button>
      )}
    </div>
  )
}
